### PR TITLE
changes  to challenge 15

### PR DESCRIPTION
**Pull request by marigerr**
PR suggestion to change Challenge 15 to possibly be a more intuitive/real-world example of how to pass an array as props.  Referenced this on June 30 in [General Feedback issue](https://github.com/bonham000/fcc-react-tests-module/issues/202).  (I had commented then from a different github account)

### CODE REVIEW

**Comment by no-stack-dub-sack** [comment]
@marigerr @bonham000 So I think this looks good for the most part, but I do have a couple of comments. The main one being the concepts used in the challenge:

Thinking back, I think this is why I struggled to come up with a basic real world-ish example using arrays, because one of the most common use cases in React is mapping over them to create UI elements. I would have gone with an example similar to this myself, however, this challenge is pretty early on, and the whole point is just to illustrate the concept that you _can_ pass other data types, such as arrays, but _not_ to illustrate the full power of what they're capable of. 

In general, we've been careful not to introduce more complex concepts that we don't explain, and we don't introduce the possibilities of arrays and `map` until much later in the curriculum, and I think this could possibly confuse some newer campers - especially if they are over-zealous and decide to attack React before having an underlying understanding of JavaScript. 

A couple of options here I think:
- we could still go with this, but not mention `map` in the instructions, i.e. just leave it as part of the boilerplate code and let them either take it for granted or investigate on their own
- use the TODO example w/o `map`: use a `<ol>` instead of of `<ul>` and just use bracket notation to access the three options.
- come up with a new, even more basic example that might be less confusing then mine and that doesn't use `map` which just illustrates the point of passing arrays as props

If we go with the first or second options, I might have a couple of other comments around the instructions language, but I think maybe we tackle this bigger question first.

**Comment by bonham000** [comment]
@marigerr thanks for the PR! Overall I think this is a great effort but agree with @no-stack-dub-sack's comments. Another option to circumvent `.map` would be something simple like `<p>{items.join(', ')}</p>` to just stringify them basically to avoid having to introduce/rely on another concept here.

**Comment by marigerr** [comment]
Thanks for reviewing!  I had same thoughts about using `map  `and also the way the example builds the component in two steps.  But thought that the example was somewhat straightforward and that IF campers follow the progression they get `array.map `before they hit React.   But not always the case, like you say and definitely understand the goals of making bite-size incremental learning.  
Both of your  suggestions sound good.   I think I like @bonham000 's idea best with replacing `map ` function with  `<p>{items.join(', ')}</p>`   But can update the PR for review in the direction you guys decide..

**Comment by bonham000** [comment]
@marigerr go ahead and revise it and we'll review again! There were some minor things I also saw about consistency in the language and instructions, but they're just details that we can iron out later.

**Comment by marigerr** [comment]
Okdoke, added 2nd commit to use join() instead of map().   Hopefully headed in right direction :)

**Comment by bonham000** [comment]
Hey @marigerr this looks great to me. I made a few minor revisions and realized I can't update this PR directly so I just pushed my code [into a new PR](https://github.com/bonham000/fcc-react-tests-module/pull/222) with the changes I made. Let me know what you think, we can merge that if you are OK with everything and then update the challenges! Thanks.

FYI @no-stack-dub-sack

**Comment by bonham000** [comment]
Ok, great I'm going to merge this and update the site! Thanks for the work @marigerr.

**Pull request merged**
