### PR TITLE
React 04

### PR DESCRIPTION
**Pull request by benschac**
Updates Challenge Code and Instructions to complete the challenge.

### CODE REVIEW

**Comment by bonham000** [comment]
Hey @benschac I've manually merged in some pieces from these pull requests you've opened but I didn't merge everything. We've had some other Free Code Camp core team members review the language on these challenges and they've already passed the initial review/revision process so in many cases the language and wording probably should not change dramatically. However, I did apply some revisions based on what you pointed out (notably about the misspelling of 'apend'). I would recommend the best way to bring up any proposed changes would be to open an issue first unless you find something that is clearly a typo or bug. Thanks for your feedback on these challenges so far!

**Comment by benschac** [comment]
ah bummer! Which repo should I open an issue in? This one?  Not that I know
think the content is good, it is.  I can tell a lot of time was spent on
it.  From using it and reading through it for hours at a time it feels like
it could be a little more direct.  My one other concern is when the
language simply is used so often.  This stuff is super hard and at time not
really that clear to folks just starting out.

**Comment by bonham000** [comment]
@benschac I would definitely open an issue here if it is a concern related to the language and content of these challenges.

**Comment by benschac** [comment]
Okay, I'd still like to go through and make small tweaks if that's cool, or
should I start chatting in the curriculum room?

**Pull request closed without merging**
