### PR TITLE
Rename files with integers less than 10 to include leading 0 for prop…

### PR DESCRIPTION
**Pull request by jboxman**
A minor change to the filenames so that they appear in order in a directory listing.

### CODE REVIEW

**Comment by bonham000** [comment]
Cool thanks!

**Comment by jboxman** [comment]
Except I think I broke it -- can you confirm if it works for you after this? I seem to have missed references to original convention somewhere.

**Comment by bonham000** [comment]
I just fixed it and updated.

**Comment by bonham000** [comment]
@jboxman do you want to help Peter and I with writing these challenges?

**Comment by jboxman** [comment]
Yeah, belatedly working in that direction. Haven't they mostly been written at this point and just need to be imported into this so unit tests can be written for them?

If you want me to work on specific challenges let me know so we don't collide.

Thanks!

**Comment by bonham000** [comment]
So some work has been done but they're definitely not finished yet and 0 have tests written which is probably the most time-consuming part. So Peter and I have pulled what existed on the GitHub Issues here and are modifying it on the fly as we go, more or less. I'm trying to pull in content that has already been written but a lot I'm just writing from scratch.

The `Challenges_Map` is our rough outline as we go. For the moment, if you want to help you could take the first challenge under State: Define the initial state within the component's constructor.

I think if you've been looking through the code it should be straightforward how we are writing to the challenges but please just comment or message me on Gitter if you have any specific questions.

**Pull request merged**
